### PR TITLE
Topic as a Trait

### PR DESCRIPTION
**Pull request by bfrog**
Adds a trait to represent the functionality a pub/sub topic may require to allow for multiple bus implementations which may have different delimiters, wildcards, or matchany syntaxes

### CODE REVIEW

**Review by corynguyenfl — APPROVED** [review]
Looks good to me

**Comment by bfrog** [comment]
I need to fix the nats topic mapping stuff I think, some missing things I just realized as I walked away

**Review by jmager-oes — APPROVED** [review]
Interesting, thanks for sharing.

**Comment by bfrog** [comment]
Added a test case for mapping to/from a nats subject string to something that implements a Topic.

From a subject string to a Topic should require zero to few allocations (no string copying).

**Pull request merged**
